name: Setup wgpu4k
description: Restore wgpu4k dependencies from cache, pre-built release, or build from source

inputs:
  rust-targets:
    description: Extra Rust targets for cross-compilation (comma-separated, e.g. aarch64-apple-ios,aarch64-apple-ios-sim)
    required: false
    default: ""

outputs:
  version:
    description: wgpu4k version string
    value: ${{ steps.deps-version.outputs.wgpu4k_version }}
  commit:
    description: wgpu4k commit hash
    value: ${{ steps.deps-version.outputs.wgpu4k_commit }}
  cache-hit:
    description: Whether dependencies were restored from cache
    value: ${{ steps.cache-deps.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Read dependency versions
      id: deps-version
      shell: bash
      run: |
        extract() { grep "^$1" gradle/libs.versions.toml | grep -v '{' | sed 's/.*"\(.*\)".*/\1/'; }

        WGPU4K_VERSION=$(extract 'wgpu4k ')
        WGPU4K_COMMIT=$(extract 'wgpu4kCommit')
        WGPU4K_REPO=$(extract 'wgpu4kRepo')
        NATIVE_COMMIT=$(extract 'wgpu4kNativeCommit')
        NATIVE_REPO=$(extract 'wgpu4kNativeRepo')
        KTYPES_COMMIT=$(extract 'webgpuKtypesCommit')
        KTYPES_REPO=$(extract 'webgpuKtypesRepo')

        for var in WGPU4K_VERSION WGPU4K_COMMIT WGPU4K_REPO NATIVE_COMMIT NATIVE_REPO KTYPES_COMMIT KTYPES_REPO; do
          if [ -z "${!var}" ]; then
            echo "::error::Failed to extract $var from libs.versions.toml"
            exit 1
          fi
        done

        # Short hashes for cache key (first 8 chars of each)
        CACHE_HASH="${KTYPES_COMMIT:0:8}-${NATIVE_COMMIT:0:8}-${WGPU4K_COMMIT:0:8}"

        echo "wgpu4k_version=$WGPU4K_VERSION" >> "$GITHUB_OUTPUT"
        echo "wgpu4k_commit=$WGPU4K_COMMIT" >> "$GITHUB_OUTPUT"
        echo "wgpu4k_repo=$WGPU4K_REPO" >> "$GITHUB_OUTPUT"
        echo "native_commit=$NATIVE_COMMIT" >> "$GITHUB_OUTPUT"
        echo "native_repo=$NATIVE_REPO" >> "$GITHUB_OUTPUT"
        echo "ktypes_commit=$KTYPES_COMMIT" >> "$GITHUB_OUTPUT"
        echo "ktypes_repo=$KTYPES_REPO" >> "$GITHUB_OUTPUT"
        echo "cache_hash=$CACHE_HASH" >> "$GITHUB_OUTPUT"

        echo "wgpu4k: $WGPU4K_VERSION @ $WGPU4K_REPO/$WGPU4K_COMMIT"
        echo "wgpu4k-native: $NATIVE_REPO/$NATIVE_COMMIT"
        echo "webgpu-ktypes: $KTYPES_REPO/$KTYPES_COMMIT"

    - name: Cache wgpu dependencies (Maven Local)
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository/io/ygdrasil
          ~/.m2/repository/com/hyeons-lab
        key: wgpu-deps-${{ runner.os }}-${{ steps.deps-version.outputs.cache_hash }}

    - name: Download pre-built artifacts from GitHub Release
      id: release-download
      if: steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_TAG: wgpu4k-deps-v${{ steps.deps-version.outputs.cache_hash }}
      run: |
        ASSET_NAME="wgpu4k-deps-${RUNNER_OS}.tar.zst"
        echo "Trying to download $ASSET_NAME from release $RELEASE_TAG..."

        DL_OUTPUT=$(gh release download "$RELEASE_TAG" --pattern "$ASSET_NAME" --dir /tmp --repo "$GITHUB_REPOSITORY" 2>&1) && DL_OK=true || DL_OK=false

        if [ "$DL_OK" = "true" ]; then
          echo "::group::Extract pre-built artifacts"
          mkdir -p ~/.m2/repository
          tar --zstd -xf "/tmp/$ASSET_NAME" -C ~/.m2/repository
          rm -f "/tmp/$ASSET_NAME"
          echo "::endgroup::"

          echo "downloaded=true" >> "$GITHUB_OUTPUT"
          echo "Pre-built artifacts restored from release $RELEASE_TAG"
        elif echo "$DL_OUTPUT" | grep -qi "not found\|no assets\|release not found"; then
          echo "downloaded=false" >> "$GITHUB_OUTPUT"
          echo "Release asset not available — will build from source"
        else
          echo "::warning::gh release download failed unexpectedly: $DL_OUTPUT"
          echo "downloaded=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Set up Rust toolchain
      if: steps.cache-deps.outputs.cache-hit != 'true' && steps.release-download.outputs.downloaded != 'true'
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.rust-targets }}

    - name: Cache Rust toolchain
      if: steps.cache-deps.outputs.cache-hit != 'true' && steps.release-download.outputs.downloaded != 'true'
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: wgpu4k-rust

    # Build order: webgpu-ktypes first, then wgpu4k-native, then wgpu4k (depends on both)

    - name: Build webgpu-ktypes from source
      if: steps.cache-deps.outputs.cache-hit != 'true' && steps.release-download.outputs.downloaded != 'true'
      shell: bash
      env:
        REPO: ${{ steps.deps-version.outputs.ktypes_repo }}
        COMMIT: ${{ steps.deps-version.outputs.ktypes_commit }}
      run: |
        echo "::group::Clone webgpu-ktypes"
        git init /tmp/webgpu-ktypes
        cd /tmp/webgpu-ktypes
        git remote add origin "https://github.com/${REPO}.git"
        git fetch --depth 1 origin "$COMMIT"
        git checkout FETCH_HEAD
        echo "::endgroup::"

        echo "::group::Build webgpu-ktypes"
        START=$SECONDS
        ./gradlew publishToMavenLocal --no-daemon
        echo "webgpu-ktypes build: $((SECONDS - START))s"
        echo "::endgroup::"

    - name: Build wgpu4k-native from source
      if: steps.cache-deps.outputs.cache-hit != 'true' && steps.release-download.outputs.downloaded != 'true'
      shell: bash
      env:
        REPO: ${{ steps.deps-version.outputs.native_repo }}
        COMMIT: ${{ steps.deps-version.outputs.native_commit }}
      run: |
        echo "::group::Clone wgpu4k-native"
        git init /tmp/wgpu4k-native
        cd /tmp/wgpu4k-native
        git remote add origin "https://github.com/${REPO}.git"
        git fetch --depth 1 origin "$COMMIT"
        git checkout FETCH_HEAD
        echo "::endgroup::"

        echo "::group::Build wgpu4k-native"
        START=$SECONDS
        ./gradlew publishToMavenLocal --no-daemon
        echo "wgpu4k-native build: $((SECONDS - START))s"
        echo "::endgroup::"

    - name: Build wgpu4k from source
      if: steps.cache-deps.outputs.cache-hit != 'true' && steps.release-download.outputs.downloaded != 'true'
      shell: bash
      env:
        REPO: ${{ steps.deps-version.outputs.wgpu4k_repo }}
        COMMIT: ${{ steps.deps-version.outputs.wgpu4k_commit }}
      run: |
        echo "::group::Clone wgpu4k"
        git init /tmp/wgpu4k
        cd /tmp/wgpu4k
        git remote add origin "https://github.com/${REPO}.git"
        git fetch --depth 1 origin "$COMMIT"
        git checkout FETCH_HEAD
        echo "::endgroup::"

        echo "::group::Build wgpu4k"
        START=$SECONDS
        ./gradlew publishToMavenLocal --no-daemon -x dokkaHtml -x dokkaGenerate -x dokkaGenerateHtml
        echo "wgpu4k build: $((SECONDS - START))s"
        echo "::endgroup::"

    - name: Build summary
      if: steps.cache-deps.outputs.cache-hit != 'true' && steps.release-download.outputs.downloaded != 'true'
      shell: bash
      run: |
        echo "### wgpu Dependencies Build" >> "$GITHUB_STEP_SUMMARY"
        echo "| Group | Files | Size |" >> "$GITHUB_STEP_SUMMARY"
        echo "|-------|-------|------|" >> "$GITHUB_STEP_SUMMARY"
        for GROUP_PATH in io/ygdrasil com/hyeons-lab; do
          DIR=~/.m2/repository/$GROUP_PATH
          if [ -d "$DIR" ]; then
            COUNT=$(find "$DIR" -type f | wc -l | tr -d ' ')
            SIZE=$(du -sh "$DIR" | cut -f1)
            GROUP=$(echo "$GROUP_PATH" | tr '/' '.')
            echo "| \`${GROUP}\` | ${COUNT} files | ${SIZE} |" >> "$GITHUB_STEP_SUMMARY"
          fi
        done

    - name: Cache status diagnostics
      shell: bash
      env:
        WGPU4K_VERSION: ${{ steps.deps-version.outputs.wgpu4k_version }}
        WGPU4K_COMMIT: ${{ steps.deps-version.outputs.wgpu4k_commit }}
        NATIVE_COMMIT: ${{ steps.deps-version.outputs.native_commit }}
        KTYPES_COMMIT: ${{ steps.deps-version.outputs.ktypes_commit }}
        CACHE_HIT: ${{ steps.cache-deps.outputs.cache-hit }}
        RELEASE_DOWNLOAD: ${{ steps.release-download.outputs.downloaded }}
        CACHE_HASH: ${{ steps.deps-version.outputs.cache_hash }}
      run: |
        if [ "$CACHE_HIT" = "true" ]; then
          SOURCE="actions/cache"
        elif [ "$RELEASE_DOWNLOAD" = "true" ]; then
          SOURCE="GitHub Release"
        else
          SOURCE="built from source"
        fi

        echo "### wgpu Dependency Cache" >> "$GITHUB_STEP_SUMMARY"
        echo "| Key | Value |" >> "$GITHUB_STEP_SUMMARY"
        echo "|-----|-------|" >> "$GITHUB_STEP_SUMMARY"
        echo "| wgpu4k | \`${WGPU4K_VERSION}\` @ \`${WGPU4K_COMMIT:0:8}\` |" >> "$GITHUB_STEP_SUMMARY"
        echo "| wgpu4k-native | \`${NATIVE_COMMIT:0:8}\` |" >> "$GITHUB_STEP_SUMMARY"
        echo "| webgpu-ktypes | \`${KTYPES_COMMIT:0:8}\` |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Cache key | \`wgpu-deps-${RUNNER_OS}-${CACHE_HASH}\` |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Source | ${SOURCE} |" >> "$GITHUB_STEP_SUMMARY"
