import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
  id("prism-quality")
  alias(libs.plugins.kotlin.multiplatform)
  alias(libs.plugins.android.kotlin.multiplatform.library)
  alias(libs.plugins.skie)
  alias(libs.plugins.maven.publish)
}

kotlin {
  jvmToolchain(25)
  android {
    namespace = "com.hyeonslab.prism.flutter"
    compileSdk = libs.versions.compileSdk.get().toInt()
    minSdk = libs.versions.minSdk.get().toInt()
  }
  iosArm64()
  iosSimulatorArm64()
  val xcf = XCFramework("PrismFlutter")
  macosArm64 {
    binaries.framework {
      baseName = "PrismFlutter"
      isStatic = false
      xcf.add(this)
    }
  }
  linuxX64()
  mingwX64()

  @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class) wasmJs { browser() }

  applyDefaultHierarchyTemplate()

  sourceSets {
    commonMain.dependencies {
      api(project(":prism-core"))
      api(project(":prism-native-widgets"))
    }
    androidMain.dependencies {
      api(libs.wgpu4k.toolkit)
      implementation(libs.kotlinx.coroutines.android)
    }
    macosMain.dependencies {
      api(libs.wgpu4k.toolkit)
      implementation(libs.kotlinx.coroutines.core)
    }
    commonTest.dependencies { implementation(libs.kotlin.test) }
  }

  compilerOptions {
    allWarningsAsErrors.set(true)
    freeCompilerArgs.add("-Xexpect-actual-classes")
  }
}

// ---------------------------------------------------------------------------
// Wrap libprism.dylib into a multi-slice iOS XCFramework for SPM binary target.
// Run: ./gradlew :prism-flutter:bundleNativeiOS
// ---------------------------------------------------------------------------
tasks.register<Exec>("bundleNativeiOS") {
  val prismNative = project(":prism-native")
  val iosArm64Dir = prismNative.layout.buildDirectory.dir("bin/iosArm64/releaseShared").get().asFile
  val iosSimDir =
    prismNative.layout.buildDirectory.dir("bin/iosSimulatorArm64/releaseShared").get().asFile
  val outDir = layout.projectDirectory.dir("flutter_plugin/ios/prism_flutter/Frameworks").asFile
  dependsOn(
    ":prism-native:linkReleaseSharedIosArm64",
    ":prism-native:linkReleaseSharedIosSimulatorArm64",
  )
  commandLine(
    "xcodebuild",
    "-create-xcframework",
    "-library",
    File(iosArm64Dir, "libprism.dylib").absolutePath,
    "-headers",
    iosArm64Dir.absolutePath,
    "-library",
    File(iosSimDir, "libprism.dylib").absolutePath,
    "-headers",
    iosSimDir.absolutePath,
    "-output",
    File(outDir, "PrismNative.xcframework").absolutePath,
  )
  doFirst {
    File(outDir, "PrismNative.xcframework").deleteRecursively()
    outDir.mkdirs()
  }
}

// ---------------------------------------------------------------------------
// Auto-generate Dart @JS() bindings from the prism-js TypeScript declarations.
// Run: ./gradlew :prism-flutter:generateDartJsBindings
// ---------------------------------------------------------------------------
tasks.register("generateDartJsBindings") {
  dependsOn(":prism-js:compileProductionExecutableKotlinWasmJs")
  val dtsSrcProvider =
    project(":prism-js")
      .layout
      .buildDirectory
      .file("compileSync/wasmJs/main/productionExecutable/kotlin/prism.d.mts")
  val dartOutFile =
    layout.projectDirectory.file("flutter_plugin/lib/src/generated/prism_js_bindings.dart").asFile
  inputs.file(dtsSrcProvider)
  outputs.file(dartOutFile)

  doLast {
    val dtsContent = dtsSrcProvider.get().asFile.readText()

    fun mapType(ts: String): String =
      when (ts.trim()) {
        "string" -> "String"
        "number" -> "double"
        "boolean" -> "bool"
        "void" -> "void"
        else -> "dynamic"
      }

    fun parseParams(raw: String): String {
      if (raw.isBlank()) return ""
      return raw
        .split(",")
        .map { it.trim() }
        .filter { it.isNotEmpty() }
        .joinToString(", ") { p ->
          val parts = p.split(":")
          val name = parts[0].trim().trimEnd('?')
          val type = parts.getOrElse(1) { "string" }.trim()
          "${mapType(type)} $name"
        }
    }

    val funcRegex = Regex("""export declare function (\w+)\((.*?)\): (\w+);""")
    val functions =
      funcRegex
        .findAll(dtsContent)
        .map { m -> Triple(m.groupValues[1], m.groupValues[2], m.groupValues[3]) }
        .toList()

    val sb = StringBuilder()
    sb.appendLine("// AUTO GENERATED FILE, DO NOT EDIT.")
    sb.appendLine("// Generated by :prism-flutter:generateDartJsBindings from prism.d.mts")
    sb.appendLine("// ignore_for_file: type=lint")
    sb.appendLine("import 'dart:js_interop';")
    sb.appendLine()
    functions.forEach { (name, rawParams, retType) ->
      val dartParams = parseParams(rawParams)
      val dartRet = mapType(retType)
      sb.appendLine("@JS('PrismSdk.$name')")
      sb.appendLine("external $dartRet $name($dartParams);")
      sb.appendLine()
    }

    dartOutFile.parentFile.mkdirs()
    dartOutFile.writeText(sb.toString())
    logger.lifecycle("Dart JS bindings written to $dartOutFile")
  }
}

// ---------------------------------------------------------------------------
// Assemble PrismFlutter.xcframework (Kotlin/Native bridge) and copy into the
// generic plugin's Frameworks directory so SPM can declare it as a binary target.
// Consumers link against this instead of the demo-specific PrismFlutterDemo.xcframework.
// Run: ./gradlew :prism-flutter:bundleFlutterMacOS
// ---------------------------------------------------------------------------
tasks.register<Copy>("bundleFlutterMacOS") {
  dependsOn("assemblePrismFlutterReleaseXCFramework")
  val xcfDir = layout.buildDirectory.dir("XCFrameworks/release/PrismFlutter.xcframework")
  from(xcfDir)
  into(
    layout.projectDirectory.dir(
      "flutter_plugin/macos/prism_flutter/Frameworks/PrismFlutter.xcframework"
    )
  )
}

// ---------------------------------------------------------------------------
// Wrap libprism.dylib into an XCFramework for SPM binary target bundling.
// Run: ./gradlew :prism-flutter:bundleNativeMacOS
// ---------------------------------------------------------------------------
tasks.register<Exec>("bundleNativeMacOS") {
  val dylibDir =
    project(":prism-native").layout.buildDirectory.dir("bin/macosArm64/releaseShared").get().asFile
  val outDir = layout.projectDirectory.dir("flutter_plugin/macos/prism_flutter/Frameworks").asFile
  dependsOn(":prism-native:linkReleaseSharedMacosArm64")
  commandLine(
    "xcodebuild",
    "-create-xcframework",
    "-library",
    File(dylibDir, "libprism.dylib").absolutePath,
    "-headers",
    dylibDir.absolutePath,
    "-output",
    File(outDir, "PrismNative.xcframework").absolutePath,
  )
  doFirst {
    File(outDir, "PrismNative.xcframework").deleteRecursively()
    outDir.mkdirs()
    // Write module map into the headers dir so Swift can import PrismNative.
    // xcodebuild copies the entire headers dir into the XCFramework.
    File(dylibDir, "module.modulemap")
      .writeText("module PrismNative {\n    umbrella header \"libprism_api.h\"\n    export *\n}\n")
  }
}

// ---------------------------------------------------------------------------
// Copy libprism.so (Kotlin/Native) into the Android plugin's jniLibs directory.
// Split into two Copy tasks so all inputs/outputs are declared at configuration
// time — required for Gradle configuration cache compatibility.
// Run: ./gradlew :prism-flutter:bundleNativeAndroid
// ---------------------------------------------------------------------------
val prismNativeBuildDir = project(":prism-native").layout.buildDirectory

tasks.register<Copy>("bundleNativeAndroidArm64") {
  dependsOn(":prism-native:linkReleaseSharedAndroidNativeArm64")
  from(prismNativeBuildDir.file("bin/androidNativeArm64/releaseShared/libprism.so"))
  into(layout.projectDirectory.dir("flutter_plugin/android/src/main/jniLibs/arm64-v8a"))
}

tasks.register<Copy>("bundleNativeAndroidX64") {
  dependsOn(":prism-native:linkReleaseSharedAndroidNativeX64")
  from(prismNativeBuildDir.file("bin/androidNativeX64/releaseShared/libprism.so"))
  into(layout.projectDirectory.dir("flutter_plugin/android/src/main/jniLibs/x86_64"))
}

tasks.register("bundleNativeAndroid") {
  dependsOn("bundleNativeAndroidArm64", "bundleNativeAndroidX64")
}

// ---------------------------------------------------------------------------
// Copy libprism.so (Kotlin/Native, linuxX64) into the Flutter Linux plugin's
// bundled-libraries directory. CMakeLists.txt under flutter_plugin/linux/
// reads from native/libprism.so and arranges for it to land in the host
// app's lib/ directory at build time.
// Run: ./gradlew :prism-flutter:bundleNativeLinux
// ---------------------------------------------------------------------------
tasks.register<Copy>("bundleNativeLinux") {
  dependsOn(":prism-native:linkReleaseSharedLinuxX64")
  from(prismNativeBuildDir.file("bin/linuxX64/releaseShared/libprism.so"))
  into(layout.projectDirectory.dir("flutter_plugin/linux/native"))
}

// ---------------------------------------------------------------------------
// Copy prism.dll (Kotlin/Native, mingwX64) into the Flutter Windows plugin's
// bundled-libraries directory. CMakeLists.txt under flutter_plugin/windows/
// reads from native/prism.dll and Flutter copies it next to the host
// executable at build time.
// Run: ./gradlew :prism-flutter:bundleNativeWindows
// ---------------------------------------------------------------------------
tasks.register<Copy>("bundleNativeWindows") {
  dependsOn(":prism-native:linkReleaseSharedMingwX64")
  from(prismNativeBuildDir.file("bin/mingwX64/releaseShared/prism.dll"))
  into(layout.projectDirectory.dir("flutter_plugin/windows/native"))
}

mavenPublishing {
  publishToMavenCentral()
  signAllPublications()
  pom {
    description.set("Flutter bridge for the Prism engine (MethodChannel + platform views, WASM)")
  }
}
