name: PrismiOSDemo
options:
  bundleIdPrefix: com.hyeonslab.prism.ios
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  PrismiOSDemo:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.hyeonslab.prism.ios.demo
        PRODUCT_NAME: PrismiOSDemo
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/../prism-demo/build/XCFrameworks/debug"
    dependencies:
      - framework: "../prism-demo/build/XCFrameworks/debug/PrismDemo.xcframework"
      - sdk: MetalKit.framework
      - sdk: Metal.framework
